### PR TITLE
[Draft] - Primary Addin and rewrite of functions in Serverlib

### PR DESCRIPTION
**Pull request by Ethryan**
Looking for assistance to port this and update the ServerUtilities with newer features.

Nice to haves:
serverutils.integration <-- NEI, Journeymap and so on. Needs to be written from scratch.

### CODE REVIEW

**Comment by Ethryan** [comment]
Now if I only could get the icons to load...

**Comment by Ethryan** [comment]
Aurora is set to be disabled by default

**Comment by Ethryan** [comment]
Aurora is not working right now, it only shows a white page on startup, but at least it should work after some troubleshooting.

**Comment by Lyfts** [comment]
Backup command works, need to add the auto backup. All of it could also use a cleanup.

**Comment by Ethryan** [comment]
Major bug left: All commands seems to be added twice to the command list. Probably the same issue that the buttons had about being added twice, so something is calling the client function twice somehow.

Aaand, buttons are gone, again...

**Comment by Ethryan** [comment]
The Aurora Config still needs fixing, the Enum values can't be set, and i can't get it to work...

**Comment by Ethryan** [comment]
TODO: Create a way to Authorize users so that they can access the Requires_Auth pages.

**Comment by Lyfts** [comment]
The problem with commands seem to be here: https://github.com/GTNewHorizons/ServerUtilities/blob/4f6d13c8d11a4f09b743284f3f7b7b77da907814/src/main/java/serverutils/utils/ServerUtilities.java#L120
It seems to got through that once per mod in the package for whatever reason. Just like the sidebar buttons.

**Comment by Ethryan** [comment]
Damn, at least you found the root of the issue

**Comment by Lyfts** [comment]
This will crash on server startup with AromaCore loaded (and presumably more)
<details>
<summary>this</summary>

https://github.com/GTNewHorizons/ServerUtilities/blob/2684331b1e513ce0cacc7ecfd7c9c3c4a972de0f/src/main/java/serverutils/utils/ranks/CommandOverride.java#L41-L50
</details>

[crash-2023-10-03_14.28.44-server.txt](https://github.com/GTNewHorizons/ServerUtilities/files/12793406/crash-2023-10-03_14.28.44-server.txt)


Some more minor bugs:
The [Click Here] to turn notification off that shows when you join a server and aren't in a team doesn't work.
Sidebar buttons doesn't show in NEI creative+ inventory. (its not an instance of InventoryEffectRenderer)
The config option "show_playtime" is hilariously off.
The nbt and trash can keybinds don't work no matter which key you set it to.

**Comment by Ethryan** [comment]
Closing this since a new pull request has been made.

**Pull request closed without merging**
