### PR TITLE
Add option to only backup claimed chunks

### PR DESCRIPTION
**Pull request by Lyfts**
I didn't feel like dealing with the merge conflicts so it's currently based on #100 and will be drafted for now,

This extracts only the chunks that are claimed and saves them to a temporary region file which then gets zipped up, the final result is much much smaller than your usual backup and created in a fraction of the time.

Here is two chunks about to be mercilessly blown up, the one on the left is claimed and the one on the right is not. Above them is a chest full of delicious melon.
pre

This is after several OSHA violations occured and is also when the backup was taken.
explode

And finally we have the chunks after the backup was restored. This shows that only the claimed chunk remained in it's previous state while the unclaimed one was regenerated from new. (two of the obisidian lines were outside the chunk border)
<details>
  <summary>The melons survived too</summary>
  		
melon

</details>

post

<details>
  <summary>Old test which showed a mysterious patch of mossy cobble regenerating in the claimed chunk</summary>
  
  This line of tnt is directly on a chunk border between a claimed (on the left side of the tnt) and an unclaimed chunk 
tnt_line

This is the result of the explosion
post_explosion

And this is after restoring from a backup, showing that only the claimed chunk on the left remained the same while the unclaimed regenerated from new. For unknown reasons Minecraft generated a patch of mossy cobble in the claimed chunk after restoring from backup, which will need to be investigated.

post_backup
  
</details>

Closes https://github.com/GTNewHorizons/ServerUtilities/issues/75

### CODE REVIEW

**Comment by Lyfts** [comment]
Just tested this on my old UMV world where it brought the backup size down from 3.2GB to just <ins>**34MB**</ins> whilst keeping my entire base & all my many random claims intact and working. 

It was small enough that it only took a staggering 5 seconds to [upload it as proof](https://www.dropbox.com/scl/fi/vg7cy2e3apcxmyn9lxfum/2024-08-06-19-10-52.zip?rlkey=wrldpklxvlrsyp9cybs66vwsy&st=rqv6ompy&dl=0) if anyone wants to check it out

**Comment by S4mpsa** [comment]
This should require a Void Miner controller to enable, otherwise it provides infinite resources 👏

**Comment by Caedis** [comment]
@S4mpsa if people are purposely restoring backups, they might as well give themself creative mode

**Comment by awolosewicz** [comment]
> This should require a Void Miner controller to enable, otherwise it provides infinite resources 👏

Couldn't someone who wanted to do this just manually delete the chunks/dimension anyway to force a regen? Meanwhile, I would like to decrease the size of my IV-tier 1.8GB backups

**Comment by S4mpsa** [comment]
It was more of a joke, I don't think we can enforce config options with in-game progression 😅

**Comment by jusvit** [comment]
```
Exception in thread "Thread-36" [22:04:07] [Thread-36/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: com/gtnewhorizon/gtnhlib/util/CoordinatePacker
[22:04:07] [Thread-36/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at RFB-Launch//serverutils.lib.math.ChunkDimPos.toRegionLong(ChunkDimPos.java:87)
[22:04:07] [Thread-36/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at RFB-Launch//serverutils.task.backup.ThreadBackup.lambda$mapClaimsToRegion$2(ThreadBackup.java:227)
[22:04:07] [Thread-36/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.HashMap$KeySet.forEach(Unknown Source)
[22:04:07] [Thread-36/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at RFB-Launch//serverutils.task.backup.ThreadBackup.mapClaimsToRegion(ThreadBackup.java:226)
[22:04:07] [Thread-36/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at RFB-Launch//serverutils.task.backup.ThreadBackup.backupRegions(ThreadBackup.java:154)
[22:04:07] [Thread-36/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at RFB-Launch//serverutils.task.backup.ThreadBackup.doBackup(ThreadBackup.java:86)
[22:04:07] [Thread-36/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at RFB-Launch//serverutils.task.backup.ThreadBackup.run(ThreadBackup.java:64)
[22:04:07] [Thread-36/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: Class bytes are null for com.gtnewhorizon.gtnhlib.util.CoordinatePacker (com.gtnewhorizon.gtnhlib.util.CoordinatePacker, com.gtnewhorizon.gtnhlib.util.CoordinatePacker)
[22:04:07] [Thread-36/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 7 more
```

When trying to backup a 6GB world with like 14 teams.

I DM'ed you the world file on discord.

**Comment by Caedis** [comment]
@jusvit you need to update gtnhlib

**Comment by jusvit** [comment]
# Results for 6GB Server world with 19 teams (~25 players)

## Log
[Server Utilities]: Backed up 103 regions containing 3408 claimed chunks
[Server Utilities]: Backup done in 00:19 seconds (94.5MB)!

## Results
Not good, chunks are mix and matched, looks like the matrix.

Although the zip size is 98.471% decrease from a complete backup :)

This should be flat grass (personal dimension) but it seems to have sections of the nether, and the overworld.
image

This is the overworld but it has my personal dimension base there.
image

This is my personal dimension, it seems to have my moon base, a bit of my original overworld base, some nether chunks and my actual base at the back.
image

Not sure what's going on, I think the claims were copied to each dimensions and overlapped.
The original bases (in their actual location) all seem good and dandy.

I can provide you the world if you want, I sent you a friend request on discord, accept if you want the world.

**Comment by jusvit** [comment]
Fixes look good, chunks are as-expected.

**Comment by Caedis** [comment]
Is this going to be default on?

**Comment by Lyfts** [comment]
Nah it will be disabled by default

**Comment by Dream-Master** [comment]
@Lyfts i open this because #100 is now approved and merged .

**Review by Ethryan — APPROVED** [review]
LGTM

**Pull request merged**
